tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0b1326',
        surface: '#0f1a30',
        'surface-dim': '#0b1326',
        'surface-bright': '#32405c',
        'surface-container-lowest': '#070d1c',
        'surface-container-low': '#111d38',
        'surface-container': '#152441',
        'surface-container-high': '#1b2c4d',
        'surface-container-highest': '#233459',
        'surface-variant': '#3e4850',
        'surface-tint': '#5b8def',
        'on-surface': '#e7ecf7',
        'on-surface-variant': '#a8b3cc',
        'on-background': '#e7ecf7',
        primary: '#5b8def',
        'on-primary': '#04101f',
        'primary-container': '#1f3a68',
        'on-primary-container': '#cfe0ff',
        'primary-fixed-dim': '#a9c6ff',
        secondary: '#4ae176',
        'on-secondary': '#04220f',
        'secondary-container': '#153a24',
        'on-secondary-container': '#c3f5d3',
        'secondary-fixed': '#4ae176',
        tertiary: '#fa9417',
        'on-tertiary': '#2b1600',
        'tertiary-container': '#4d2f06',
        'on-tertiary-container': '#ffdbab',
        'tertiary-fixed-dim': '#ffb866',
        error: '#ff5a5f',
        'on-error': '#2b0000',
        'error-container': '#4a1414',
        'on-error-container': '#ffd9d9',
        outline: '#7c8aa5',
        'outline-variant': '#2b3854',
      },
      fontFamily: {
        'headline': ['"Hanken Grotesk"', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'data-display': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-sm': ['16px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.5' }],
        'body-md': ['14px', { lineHeight: '1.5' }],
        'label-caps': ['11px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '600' }],
        'data-display': ['15px', { lineHeight: '1.3' }],
      },
      spacing: {
        base: '6px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
    },
  },
};
